services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8000:80
    networks:
      - default

  db:
    image: mariadb
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/db-init:/docker-entrypoint-initdb.d
    env_file:
      - ./database.env

  web:
    depends_on:
      - db
    networks:
      - default

  celery-worker:
    depends_on:
      - db
    networks:
      - default

  celery-beat:
    depends_on:
     - db
    networks:
      - default

  start_dependencies:
    build: ./docker/start_dependencies
    depends_on:
      - web
    command: db:3306 /var/run/python/uwsgi.sock
    volumes:
      - python_sock:/var/run/python
