networks:
  redis:
    driver: bridge

volumes:
  python_sock:
  nginx_logs:

services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    depends_on:
      - web
    volumes:
      - ./backend/static:/var/www/backend/static
      - ./backend/media:/var/www/backend/media
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_logs:/var/log/nginx
      - python_sock:/var/run/python

  web:
    build:
      context: ./docker/web
      target: runtime_base
    volumes:
      - ./backend:/var/www/backend
      - python_sock:/var/run/python
    env_file:
      - ./database.env
      - ./web.env
    networks:
      - redis

  celery-worker:
    restart: unless-stopped
    build:
      context: ./docker/web
      target: runtime_base
    command: [ "celery", "-A", "main", "worker", "-l", "INFO", "-f", "/dev/stderr" ]
    volumes:
      - ./backend:/var/www/backend
    env_file:
      - ./database.env
      - ./web.env
    networks:
      - redis
    depends_on:
      - redis

  celery-beat:
    restart: unless-stopped
    build:
      context: ./docker/web
      target: runtime_base
    command: [ "celery", "-A", "main", "beat", "-l", "INFO", "-f", "/dev/stderr" ]
    volumes:
      - ./backend:/var/www/backend
    env_file:
      - ./database.env
      - ./web.env
    networks:
      - redis
    depends_on:
      - redis

  redis:
    restart: unless-stopped
    image: redis:6-alpine
    networks:
      - redis
