# Generated by Django 4.2.5 on 2023-11-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=128, null=True)),
                ('city_code', models.SmallIntegerField(blank=True, null=True)),
                ('en_city_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Prefectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('en_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prefectures',
            },
        ),
        migrations.CreateModel(
            name='Corporations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13, unique=True)),
                ('process', models.CharField(max_length=2)),
                ('correct', models.BooleanField()),
                ('update_date', models.DateField()),
                ('change_date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('name_image_id', models.CharField(blank=True, max_length=8, null=True)),
                ('kind', models.SmallIntegerField()),
                ('street_number', models.CharField(blank=True, max_length=128, null=True)),
                ('address_image_id', models.CharField(blank=True, max_length=8, null=True)),
                ('post_code', models.CharField(blank=True, max_length=7, null=True)),
                ('address_outside', models.CharField(blank=True, max_length=512, null=True)),
                ('address_outside_image_id', models.CharField(blank=True, max_length=8, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('close_cause', models.CharField(blank=True, max_length=2, null=True)),
                ('successor_number', models.CharField(blank=True, max_length=13, null=True)),
                ('change_cause', models.TextField(blank=True, null=True)),
                ('assignment_date', models.DateField()),
                ('latest', models.BooleanField()),
                ('en_name', models.CharField(blank=True, max_length=256, null=True)),
                ('en_address_outside', models.CharField(blank=True, max_length=128, null=True)),
                ('furigana', models.CharField(blank=True, max_length=256, null=True)),
                ('hihyoji', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search_engine.cities')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search_engine.prefectures')),
            ],
            options={
                'db_table': 'corporations',
                'indexes': [models.Index(fields=['number', 'name'], name='corporation_number_713cc1_idx')],
            },
        ),
    ]
