# Generated by Django 4.2.5 on 2023-11-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='city_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='city_name',
            new_name='name',
        ),
    ]
