# Generated by Django 4.2.5 on 2024-01-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_alter_cities_code_alter_cities_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='code',
            field=models.SmallIntegerField(db_comment='Unique number of the city.'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Created at.'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='en_name',
            field=models.CharField(blank=True, db_comment='Name of the city in English.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(db_comment='Name of the city.', max_length=128),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Updated at.'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='address_image_id',
            field=models.CharField(blank=True, db_comment='Image of the company address (https://www.houjin-bangou.nta.go.jp/image?imageid=<addressImageId>).', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='address_outside',
            field=models.CharField(blank=True, db_comment='Address of the company outside of Japan.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='address_outside_image_id',
            field=models.CharField(blank=True, db_comment='Image of the company address outside of Japan (https://www.houjin-bangou.nta.go.jp/image?imageid=<addressOutsideImageId>).', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='assignment_date',
            field=models.DateField(db_comment='Date of the company assignment (date of creation of corporate number).'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='change_cause',
            field=models.TextField(blank=True, db_comment='Cause code of the company change.', null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='change_date',
            field=models.DateField(db_comment='Date of change of the record in import file.'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='city',
            field=models.ForeignKey(blank=True, db_comment='City of the company.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search_engine.cities'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='close_cause',
            field=models.CharField(blank=True, db_comment='Cause code of the company closing.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='close_date',
            field=models.DateField(blank=True, db_comment='Date of the company closing.', null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='correct',
            field=models.BooleanField(db_comment='Not sure what it is.'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Created at.'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='en_address_outside',
            field=models.CharField(blank=True, db_comment='Address of the company outside of Japan in English.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='en_name',
            field=models.CharField(blank=True, db_comment='Name of the company in English.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='furigana',
            field=models.CharField(blank=True, db_comment='Syllabic writing of the company name.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='hihyoji',
            field=models.BooleanField(db_comment='Hidden or not.'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='kind',
            field=models.SmallIntegerField(db_comment='Not sure what it is.'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='latest',
            field=models.BooleanField(db_comment='Not sure what it is.'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='name',
            field=models.CharField(db_comment='Name of the company.', max_length=256),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='name_image_id',
            field=models.CharField(blank=True, db_comment='Image of the company name (https://www.houjin-bangou.nta.go.jp/image?imageid=<nameImageId>).', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='number',
            field=models.CharField(db_comment='Unique number for each company in Japan to identify it.', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='post_code',
            field=models.CharField(blank=True, db_comment='Postal code of the company.', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='prefecture',
            field=models.ForeignKey(blank=True, db_comment='Prefecture (region of Japan) of the company.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search_engine.prefectures'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='process',
            field=models.CharField(db_comment='Consist of 2 numbers (02, 81, 32, ...), not sure what it is.', max_length=2),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='street_number',
            field=models.CharField(blank=True, db_comment='Name of the street.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='successor_number',
            field=models.CharField(blank=True, db_comment='Old corporate number of the company.', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='update_date',
            field=models.DateField(db_comment='Date of update of the record in import file.'),
        ),
        migrations.AlterField(
            model_name='corporations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Updated at.'),
        ),
        migrations.AlterField(
            model_name='prefectures',
            name='code',
            field=models.CharField(db_comment='Unique number of the prefecture.', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='prefectures',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Created at.'),
        ),
        migrations.AlterField(
            model_name='prefectures',
            name='en_name',
            field=models.CharField(db_comment='Name of the prefecture in English.', max_length=128),
        ),
        migrations.AlterField(
            model_name='prefectures',
            name='name',
            field=models.CharField(db_comment='Name of the prefecture.', max_length=128),
        ),
        migrations.AlterField(
            model_name='prefectures',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Updated at.'),
        ),
    ]
