# Generated by Django 4.2.5 on 2024-01-23 17:19

from django.db import migrations, models
import search_engine.utils


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0005_alter_cities_code_alter_cities_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicHTMLCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('upper_running_title_for_home_page', 'Upper running title for home page'), ('body_statistics_for_home_page', 'Body statistics for home page'), ('lower_running_title_for_home_page', 'Lower running title for home page')], max_length=50)),
                ('code', models.TextField(validators=[search_engine.utils.code_validator])),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dynamic_html_code',
                'ordering': [models.OrderBy(models.F('created_at'))],
            },
        ),
    ]
