# Generated by Django 4.2.5 on 2024-01-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0006_dynamichtmlcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamichtmlcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamichtmlcode',
            name='type',
            field=models.CharField(choices=[('upper_running_title_for_home_page', 'Upper running title for home page'), ('lower_running_title_for_home_page', 'Lower running title for home page')], max_length=50),
        ),
    ]
