# Generated by Django 4.2.5 on 2024-04-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0007_dynamichtmlcode_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('corporation_count', 'Corporation count'), ('prefecture_count', 'Prefecture count'), ('last_update', 'Last update'), ('last_updated_corporations_count', 'Last updated corporations count')], max_length=50, unique=True)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'statistics',
                'db_table': 'statistics',
            },
        ),
    ]
