# Generated by Django 4.2.5 on 2024-04-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0008_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='type',
            field=models.CharField(choices=[('corporation_count', 'Corporation count'), ('prefecture_count', 'Prefecture count'), ('last_update', 'Last update'), ('last_updated_corporations_count', 'Last updated corporations count'), ('youngest_corporations', 'Youngest corporations'), ('oldest_corporations', 'Oldest corporations'), ('longest_name_corporations', 'Longest name corporations'), ('foreign_corporations', 'Foreign corporations')], max_length=50, unique=True),
        ),
    ]
