# Generated by Django 4.2.5 on 2024-04-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0009_alter_statistics_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
